version: '3.4'

services:
  api:
    image: gsh-api
    container_name: gsh_api
    build:
      context: ./
      target: gsh-api
    env_file: .env
    depends_on: 
      - db
    links:
      - db:gsh_db
    ports:
      - 8000:8000
    restart: always
    
  db:
    image: mysql
    container_name: gsh_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_DATABASE:${MYSQL_DATABASE}

  keycloak:
    image: jboss/keycloak
    container_name: gsh_keycloak
    ports:
      - 8080:8080
    env_file: .env
    environment:
      - KEYCLOAK_USER:${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD:${KEYCLOAK_PASSWORD}