version: '3.4'

services:
  api:
    image: gsh-api
    container_name: gsh_api
    build:
      context: ../
      target: gsh-api
      dockerfile: docker/Dockerfile
    env_file: .env
    depends_on: 
      - db
    links:
      - db:gsh_db
    ports:
      - 8000:8000
    restart: unless-stopped
    
  db:
    image: mysql
    container_name: gsh_db
    env_file: .env
    ports:
      - "3306:3306"

  keycloak:
    image: jboss/keycloak
    container_name: gsh_keycloak
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./scripts:/tmp/scripts:ro

  target-machine:
    image: gsh-target-machine
    build:
      context: ../
      target: gsh-target-machine
      dockerfile: docker/Dockerfile
    container_name: gsh_target_machine
    links:
    - api
    ports:
      - "22000:22"
    restart: unless-stopped
